project_name: graph-indexer-cli

before:
  hooks:
    - go mod download

builds:
  - # Build macOS, Linux and Windows versions
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    targets:
      - linux_amd64
      - darwin_amd64
      - windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

dockers:
  - # GOOS of the built binary that should be used.
    goos: linux
    goarch: amd64

    # Name templates of the built binaries that should be used.
    ids: ["graph-indexer-cli"]

    # Templates of the Docker image names.
    image_templates:
      - "ghcr.io/stakemachine/graph-indexer-cli:{{ .Tag }}"
      - "ghcr.io/stakemachine/graph-indexer-cli:latest"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"